# .. seealso:: https://docs.readthedocs.io/en/stable/config-file/v2.html
version: 2
build:
  os: ubuntu-22.04
  tools:
    python:
      version: "3.12"
      install:
        - requirements: docs/requirements.txt
sphinx:
  configuration: docs/conf.py
