[tox]
envlist =
    py39
    py310
    py311
    py312
    py313
    lint
    type-check
    min
    full
    plugins
    doc
    dists
skip_missing_interpreters = true

[gh-actions]
python =
    3.9: py39
    3.10: py310
    3.11: py311
    3.12: py312
    3.13: py313, type-check, lint, plugins, min

[flake8]
exclude = .git,.tox,dist,*egg,setup.py

[testenv]
deps =
    -r{toxinidir}/requirements.txt
    -r{toxinidir}/tests/requirements.txt
    -r {toxinidir}/tests/requirements.d/base.txt
commands =
    pytest
setenv =
    PYTHONPATH = {toxinidir}/src

[testenv:lint]
deps =
    -r {toxinidir}/tests/requirements.d/lint.txt
commands =
    ruff check src --output-format pylint
    ruff check src --statistics

[testenv:lint-legacy]
deps =
    {[testenv:lint]deps}
    -r {toxinidir}/tests/requirements.d/lint-legacy.txt
commands =
    {[testenv:lint]commands}
    flake8 --doctests src tests
    - pylint --init-hook 'import os,sys; sys.path.insert(0, os.curdir)' src

[testenv:type-check]
deps =
    -r {toxinidir}/tests/requirements.d/type-check.txt
commands =
    mypy src

[testenv:full]
deps =
    {[testenv]deps}
    -r{toxinidir}/tests/requirements.d/full.txt

[testenv:plugins]
deps =
    {[testenv]deps}
    -r{toxinidir}/tests/requirements.d/plugins.txt

[testenv:doc]
allowlist_externals =
    make
deps =
    {[testenv]deps}
    -r{toxinidir}/docs/requirements.txt
commands =
        pydocstyle src
        make -C {toxinidir}/docs html
whitelist_externals =
        /usr/bin/make

[testenv:min]
deps =
    {[testenv]deps}
commands =
    pytest

[testenv:sdist]
deps =
    setuptools
commands =
    python setup.py sdist

[testenv:dists]
deps =
    {[testenv:sdist]deps}
    wheel
    twine
commands =
    {[testenv:sdist]commands}
    python setup.py bdist_wheel
    twine check dist/*-*tar.gz

# Depends: ~/.pypirc
[testenv:upload]
deps =
    {[testenv:dists]deps}
    twine
commands =
    {[testenv:dists]commands}
    twine upload --repository anyconfig dist/*

[testenv:srpm]
allowlist_externals =
    ./pkg/buildsrpm.sh
deps =
    {[testenv:sdist]deps}
commands =
    {[testenv:sdist]commands}
    ./pkg/buildsrpm.sh

[testenv:upload-copr]
allowlist_externals =
    {[testenv:srpm]allowlist_externals}
    ./pkg/copr-build.sh
deps =
    {[testenv:srpm]deps}
commands =
    {[testenv:srpm]commands}
    ./pkg/copr-build.sh

[testenv:rpms]
allowlist_externals =
    {[testenv:upload-copr]allowlist_externals}
deps =
    {[testenv:upload-copr]deps}
commands =
    {[testenv:srpm]commands}
    ./pkg/copr-build.sh check
